version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb 
    ports:
      - '3000:3000'
    volumes:
      - .:/BookMarks
      - /var/tmp
      - sockets:/BookMarks/tmp/sockets
      - public-data:/BookMarks/public
    tty: true
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: flask run --host 0.0.0.0 --port 5000
    volumes:
      - ./docker/api:/flask
      - /var/tmp
    depends_on:
      - app
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes: 
      - sockets:/BookMarks/tmp/sockets
      - public-data:/BookMarks/public
    depends_on: 
      - app

volumes:
  db_data:
  sockets:
  public-data: